/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - An odxml42 Tool
    This file WILL NOT be overwritten once changes are made.
*************************************************/
using System;
using System.ComponentModel;
                        
namespace SSoTme.OST.Lib.DataClasses
{                   
    
    public partial class TranspileRequest : ITranspileRequest
    {
        public TranspileRequest()
        {
            this.InitPoco();
        }

        public string JsonOutputFileSet { get; set; }
    }
}