/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - ssotme odxml42/odxml-to-csharp-pocos
    This file WILL NOT be overwritten once changes are made.
*************************************************/
using System;
using System.ComponentModel;
                        
namespace AIC.Lib.DataClasses
{                   
    
    public partial class ContextSkill 
    {
        public ContextSkill()
        {
            this.InitPoco();
        }

        public override String ToString()
        {
            return String.Format("ContextSkill: {0}", this.Name);
        }
                            
    }
}