/*******************************************
 Initially Generated by SSoT.me - codee42 & odxml42
 Created By: EJ Alexandra - 2017
             An Abstract Level, llc
 License:    Mozilla Public License 2.0
 *******************************************/
using System.Collections.Generic;
using SSoTme.OST.Lib.DataClasses;
using SSOTME.TestConApp.Root.TranspileHandlers;

namespace SassyMQ.SSOTME.Lib.RMQActors
{
    public interface IHandlerFactory
    {
        List<Transpiler> TranspilerList { get; }
        BaseHandler CreateHandler(SSOTMEPayload payload);
    }
}