/*******************************************
 Initially Generated by SSoT.me - codee42 & odxml42
 Created By: EJ Alexandra - 2017
             An Abstract Level, llc
 License:    Mozilla Public License 2.0
 *******************************************/
using System;
using System.Collections.Generic;

namespace SSoTme.OST.Lib.DataClasses
{
    public partial class AccountHolder
    {
        public string NonPersistentOneTimeSecret { get; set; }
    }
}