/*******************************************
 Initially Generated by SSoT.me - codee42 & odxml42
 Created By: EJ Alexandra - 2017
             An Abstract Level, llc
 License:    Mozilla Public License 2.0
 *******************************************/
using SSoTme.OST.Lib.Extensions;
using System;
using System.ComponentModel;
using System.IO;

namespace SSoTme.OST.Lib.DataClasses
{                            
    public partial class FileSet 
    {
        public FileSet()
        {
            this.InitPoco();
        }

        public void AddResourceFolder(string v)
        {
            throw new NotImplementedException();
        }

        internal void WriteTo(DirectoryInfo rootDirInfo)
        {
            this.ToXml().SplitFileSetXml(false, rootDirInfo.FullName);
        }
        // Your code goes here...
        // The "default" code is in the designer file
    }
}