/*******************************************
 Initially Generated by SSoT.me - codee42 & odxml42
 Created By: EJ Alexandra - 2017
             An Abstract Level, llc
 License:    Mozilla Public License 2.0
 *******************************************/
using SSoTme.OST.Lib.DataClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SSoTme.OST.Lib.DataClasses
{
    public class PublicAccount
    {
        public PublicAccount()
        {
            this.Transpilers = new List<Transpiler>();
        }

        public Guid AccountHolderId { get; set; }
        public String ScreenName { get; set; }
        public List<Transpiler> Transpilers { get; set; }
        public decimal? AccountSubscriptionFee { get; set; }
        public string Description { get; set; }
    }
}
