/*******************************************
 Initially Generated by SSoT.me - codee42 & odxml42
 Created By: EJ Alexandra - 2017
             An Abstract Level, llc
 License:    Mozilla Public License 2.0
 *******************************************/
using System;
using System.ComponentModel;
                        
namespace SSoTme.OST.Lib.DataClasses
{                            
    public partial class Transpiler 
    {
        public Transpiler()
        {
            this.InitPoco();
        }

        public override string ToString()
        {
            return this.DisplayName;
        }

    }
}