/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - An odxml42 Tool
    This file will not be overwritten by default!
*************************************************/
using System;
using System.ComponentModel;
                        
namespace SSoTme.OST.Lib.DataClasses
{                   
    
    public partial class TranspilerFile 
    {
        public TranspilerFile()
        {
            this.InitPoco();
        }

        public override String ToString()
        {
            return String.Format("TranspilerFile: {0}", this.Name);
        }
    }
}