/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - ssotme odxml42/odxml-to-csharp-pocos
    This file WILL NOT be overwritten once changes are made.
*************************************************/
using System;
using System.ComponentModel;
                        
namespace SSoTme.OST.Lib.DataClasses
{                   
    
    public partial class TranspileOutputFile 
    {
        public TranspileOutputFile()
        {
            this.InitPoco();
        }
                            
    }
}