/*******************************************
 Initially Generated by SSoT.me - codee42 & odxml42
 Created By: EJ Alexandra - 2017
             An Abstract Level, llc
 License:    Mozilla Public License 2.0
 *******************************************/
using System;
using System.ComponentModel;
                        
namespace SSoTme.OST.Lib.DataClasses
{                            
    public partial class TranspilerInputHint 
    {
        public TranspilerInputHint()
        {
            this.InitPoco();
        }
        // Your code goes here...
        // The "default" code is in the designer file
    }
}